name: Jekyll Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.1.9'

    - name: Install dependencies
      run: |
        gem install bundler -v '< 2'
        bundle _1.17.3_ install

    - name: Build site with Jekyll
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv _site ../_site
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv ../_site/* .
        git add .
        git commit -m "Deploy site"
        git push --force --set-upstream origin gh-pages
